//! Generator functions for setup scripts and DSV files

use camino::Utf8Path;

/// Generate package.dsv content for a package
///
/// Note: The `package_name` and `prefix` parameters are reserved for future use
/// when per-package DSV customization is implemented.
#[allow(unused_variables)]
pub fn generate_package_dsv(package_name: &str, prefix: &Utf8Path) -> String {
    let lines = vec![
        // AMENT_PREFIX_PATH
        "prepend-non-duplicate;AMENT_PREFIX_PATH;".to_string(),
        // CMAKE_PREFIX_PATH (same as AMENT_PREFIX_PATH for CMake packages)
        "prepend-non-duplicate;CMAKE_PREFIX_PATH;".to_string(),
        // PATH for bin directory
        "prepend-non-duplicate-if-exists;PATH;bin".to_string(),
        // LD_LIBRARY_PATH
        "prepend-non-duplicate-if-exists;LD_LIBRARY_PATH;lib".to_string(),
        // PYTHONPATH (common patterns)
        "prepend-non-duplicate-if-exists;PYTHONPATH;lib/python3/dist-packages".to_string(),
        "prepend-non-duplicate-if-exists;PYTHONPATH;lib/python3.10/site-packages".to_string(),
        "prepend-non-duplicate-if-exists;PYTHONPATH;lib/python3.11/site-packages".to_string(),
        "prepend-non-duplicate-if-exists;PYTHONPATH;lib/python3.12/site-packages".to_string(),
        // AMENT_CURRENT_PREFIX
        "set;AMENT_CURRENT_PREFIX;".to_string(),
    ];

    lines.join("\n")
}

/// Generate local_setup.sh content
pub fn generate_local_setup_sh(package_name: &str) -> String {
    format!(
        r#"#!/bin/bash
# This file was generated by devros
# Source this file to set up the environment for this package

eval "$(devros env shell --package {} --shell bash)"
"#,
        package_name
    )
}

/// Generate workspace setup.bash content
pub fn generate_workspace_setup_bash() -> String {
    r#"#!/bin/bash
# This file was generated by devros
# Source this file to set up the environment for the entire workspace

eval "$(devros env shell --shell bash)"
"#
    .to_string()
}
