name: 'Setup Development Environment'
description: 'Setup ROS 2 Jazzy, Rust, and other dependencies for devros'

runs:
  using: "composite"
  steps:
    - name: Setup ROS 2 Jazzy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          clang \
          cmake \
          curl \
          git \
          libssl-dev \
          lld \
          lldb \
          pkg-config \
          python3-colcon-common-extensions \
          python3-pip \
          python3-rosdep \
          ros-jazzy-ros-base \
          ssh

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Rust
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Rust components
      shell: bash
      run: |
        rustup component add rustfmt clippy rust-analyzer
