set(_AMENT_PACKAGE_NAME "example_node")
set(example_node_VERSION "0.1.0")
set(example_node_MAINTAINER "Test User <test@example.com>")
set(example_node_BUILD_DEPENDS "rclcpp" "std_msgs")
set(example_node_BUILDTOOL_DEPENDS "ament_cmake")
set(example_node_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs")
set(example_node_BUILDTOOL_EXPORT_DEPENDS )
set(example_node_EXEC_DEPENDS "rclcpp" "std_msgs")
set(example_node_TEST_DEPENDS )
set(example_node_GROUP_DEPENDS )
set(example_node_MEMBER_OF_GROUPS )
set(example_node_DEPRECATED "")
set(example_node_EXPORT_TAGS)
list(APPEND example_node_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
